format = """
[┌───](white)\
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$nodejs\
$cmd_duration $jobs\
$line_break\
[└─](white)$character\
"""

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_metrics]
disabled = false

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[fill]
symbol = " "

[nodejs]
format = '[$symbol($version )]($style)'

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[username]
show_always = true
format = '\([π]($style)\)-'
style_user = 'bold cyan'

[directory]
format = '\[[$path]($style)[$read_only]($read_only_style)\] '
style = 'bold #88baba'
read_only = " "
truncation_length = 2

[character]
success_symbol = "[❯](cyan)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"
