format = """
[┌───](white)\
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status  $jobs\
$fill\
$memory_usage\
$fill\
$cmd_duration $nodejs $golang $python $c $lua $docker_context $shell\
$line_break\
[└─](white)$character\
"""

command_timeout = 500

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_metrics]
disabled = false

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[fill]
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )($mod_version )]($style)"
symbol = " "

[python]
format = "[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)"
style = "yellow bold"
symbol = " "

[c]
format = "[$name $version]($style)"
symbol = " "

[lua]
symbol = " "
format = "[$symbol($version )]($style)"

[shell]
fish_indicator = "󰈺 "
powershell_indicator = "_"
unknown_indicator = "mystery shell"
style = "green"
disabled = false

[docker_context]
symbol = " "
style = "blue bold"
format = "[$symbol$context]($style) "
only_with_files = true

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[username]
show_always = true
format = "\([π]($style)\)-"
style_user = "bold cyan"

[directory]
format = "\[[$path]($style)[$read_only]($read_only_style)\] "
style = "bold #88baba"
read_only = "  "
truncation_length = 2

[character]
success_symbol = "[❯](cyan)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[memory_usage]
disabled = true
threshold = 75
format = "$symbol [$ram $ram_pct( | $swap)]($style) "
style = "white"
symbol = "󰍛 "

[os]
disabled = false
style = "bold white"
format = "[$symbol]($style)"
[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Debian = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
NixOS = " "
openSUSE = " "
Pop = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "
