format = """
[┌───](white)\
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status  $jobs\
$fill\
$cmd_duration $nodejs $golang $python $shell\
$line_break\
[└─](white)$character\
"""

command_timeout = 500

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_metrics]
disabled = false

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[fill]
symbol = " "

[nodejs]
format = '[$symbol($version )]($style)'

[golang]
format = '[$symbol($version )($mod_version )]($style)'
symbol = " "
detect_files = ['go.mod']

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "yellow bold"
symbol = " "

[shell]
fish_indicator = '󰈺 '
powershell_indicator = '_'
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[username]
show_always = true
format = '\([π]($style)\)-'
style_user = 'bold cyan'

[directory]
format = '\[[$path]($style)[$read_only]($read_only_style)\] '
style = 'bold #88baba'
read_only = "  "
truncation_length = 2

[character]
success_symbol = "[❯](cyan)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

