#!/bin/bash
PLUG=$(acpi -a | grep -E -o ': \w+' | cut -d ":" -f 2 | xargs)
BAT=$(acpi -b | grep -E -o '[0-9]+?%')
TEXT=""
ICON="  "
COLOR="$LAVENDER"

if [ "$PLUG" = 'on' ]; then
	ICON="" COLOR="$GREEN"
else
	[ "${BAT%?}" -le 5 ] && ICON="  " && exit 33
	[ "${BAT%?}" -le 20 ] && ICON="  " COLOR="$RED"
	[ "${BAT%?}" -le 50 ] && ICON="  " COLOR="$PEACH"
	[ "${BAT%?}" -le 70 ] && ICON="  " COLOR="$YELLOW"
	[ "${BAT%?}" -ge 70 ] && ICON="  "
fi

TEXT="$ICON $BAT"

echo "$TEXT"
echo "$ICON"
echo "$COLOR"

exit 0
